# .readthedocs.yaml
# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # Install the required dependencies
    - pip install requests
    # Run the script to download and extract the pre-built docs
    - python rtd_get_docs.py
    - echo "Documentation downloaded and extracted"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc